default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: wlapp_db_admin
  password: wlapp-db-pas
  host: localhost

development:
  <<: *default
  database: CRM_app_development

test:
  <<: *default
  database: CRM_app_test
